<a href="https://colab.research.google.com/github/AnnePet-Ameh/Hamoye/blob/main/NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np
arr = [6, 7, 8, 9]

In [1]:
import numpy as np

In [2]:
arr = [6, 7, 8, 9]

In [3]:
print(type(arr))

<class 'list'>


In [4]:
a = np.array(arr)
print(type(a))

<class 'numpy.ndarray'>


In [5]:
print(a.shape)

(4,)


In [6]:
print(a.dtype)

int64


In [7]:
print(a.ndim)

1


In [11]:
b = np.array([[1, 2, 3 ],[4, 5,6]])
print(b)

[[1 2 3]
 [4 5 6]]


In [12]:
print(b.ndim)

2


In [13]:
b.shape

(2, 3)

Built in functions

2 x 3 array with random value

In [14]:
np.random.random((2, 3))

array([[0.96361012, 0.77631008, 0.50376392],
       [0.4377323 , 0.56700903, 0.04034939]])

In [15]:
np.zeros((2, 3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [16]:
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [ ]:
#3x3 identity matrix
np.identity(3)